name: Release

on:
  release:
    types: [published]

jobs:
  build:
    name: Build and Upload Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: drast
            asset_name: drast-linux
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            bin: drast.exe
            asset_name: drast-windows.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            bin: drast
            asset_name: drast-macos

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions/setup-rust@v2
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Upload binary to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.target }}/release/${{ matrix.bin }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
