name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    name: Build and Upload Binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            bin: drast
            renamed_bin: drast_linux_x86_64_bin
            asset_name: drast_linux_x86_64_bin
          - os: windows-latest
            target: x86_64-pc-windows-gnu
            bin: drast.exe
            renamed_bin: drast_windows_x86_64_bin.exe
            asset_name: drast_windows_x86_64_bin.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            bin: drast
            renamed_bin: drast_macos_x86_64_bin
            asset_name: drast_macos_x86_64_bin

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          target: ${{ matrix.target }}

      - name: Build release
        run: cargo build --release --target ${{ matrix.target }}

      - name: Rename binary
        run: |
          mv target/${{ matrix.target }}/release/${{ matrix.bin }} target/${{ matrix.target }}/release/${{ matrix.renamed_bin }}

      - name: Upload binary to GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.target }}/release/${{ matrix.renamed_bin }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
